import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Canvas, useThree, useLoader, useFrame } from "@react-three/fiber";
import Test from "@/components/test";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // const texture = useLoader(TextureLoader, map);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Canvas shadows={true}>
        <Test />
      </Canvas>
    </>
  );
}
