import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Canvas, useThree, useLoader, useFrame } from "@react-three/fiber";
import Test from "@/components/test";
import { Suspense } from "react";
import Test2 from "@/components/test2";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // const texture = useLoader(TextureLoader, map);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Suspense fallback={<h1>Loading</h1>}>
        <Canvas shadows={true}>
          <Test2 />
        </Canvas>
      </Suspense>
      <div>Sahil E Arwand</div>
    </>
  );
}
